#!/bin/bash


user=$USER@$(hostname)
OS="Arch Linux"
Kernel="$(uname -r)"
Uptime="$(uptime -p | sed 's/up //')"
Packages="$(pacman -Q | wc -l)"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')" 
GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"

### IF statement to differentiate between Desktop Environment and Window Manager

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'

fi



# COLORS
c1="\e[31m" # Red
c2="\e[32m" # Light Green
c3="\e[33m" # Yellow
c4="\e[34m" # Calm Blue
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c7="\e[37m" # White
c8="\e[38m" # Sky Blue
c9="\e[39m" # Light Grey
c10="\e[40m" # Dark Grey
c20="\e[0m" # Normal

# An Error echo Wrapper
err0r()
{
	echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
	echo ""
	exit 86
}


# A Warning echo wrapper
warn ()
{
	echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$)tput sgr0)"
	echo ""
}



# A Message echo Wrapper
msg ()
{
	echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
}



echo ${c6}'                   -`                   '           ${c1}${user}
echo ${c6}'                  .o+`                  '           ${c1}OS:${c20}${OS}
echo ${c6}'                 `ooo/                  '           ${c1}${envtype}:${c20}${WM}
echo ${c6}'                `+oooo:                 '           ${c1}Kernel:${c20}${Kernel} 
echo ${c6}'               `+oooooo:                '           ${c1}Uptime:${c20}${Uptime}	 
echo ${c6}'               -+oooooo+:               '           ${c1}Packages:${c20}${Packages}
echo ${c6}'             `/:-:++oooo+:              '           ${c1}Shell:${c20}${Shell}
echo ${c6}'            `/++++/+++++++:             '           ${c1}CPU:${c20}${CPU}
echo ${c6}'           `/++++++++++++++:            '           ${c1}GPU:${c20}${GPU} 
echo ${c6}'          `/+++ooooooooooooo/`          '           ${c1}RAM:${c3}${RAM} 
echo ${c6}'         ./ooosssso++osssssso+`         ' 
echo ${c6}'        .oossssso-````/ossssss+`        ' 
echo ${c6}'       -osssssso.      :ssssssso.       ' 
echo ${c6}'      :osssssss/        osssso+++.      ' 
echo ${c6}'     /ossssssss/        +ssssooo/-      ' 
echo ${c6}'   `/ossssso+/:-        -:/+osssso+-    ' 
echo ${c6}'  `+sso+:-`                 `.-/+oso:   ' 
echo ${c6}' `++:.                           `-/+/  ' 
echo ${c6}' .`                                 `/  ' 
