#!/bin/sh

user=$USER@
OS="$(lsb_release -sirc)"
#Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Packages="$(dpkg -l | grep -c ^i)"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')" 
GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
IP="$(hostname -I | awk '{print $1}')"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='Desktop'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='Desktop'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'

fi


echo '          _,met$$$$$gg.        '            $user$(hostname)
echo '       ,g$$$$$$$$$$$$$$$P.     '            OS: $OS
echo '     ,g$$P""       """Y$$.".   '            $envtype: $WM		 
echo '    ,$$P"              `$$$."  '            Kernel: $Kernel
echo '   ,$$P       ,ggs.     `$$b:  '            Uptime: $Uptime
echo '  `d$$"     ,$P""   .    $$$   '            Packages: $Packages
echo '   $$P      d$"     ,    $$P   '            Shell: $Shell
echo '   $$:      $$.   -    ,d$$"   '            CPU: $CPU
echo '   $$\;      Y$b._   _,d$P     '            GPU: $GPU
echo '   Y$$.    `.`"Y$$$$P""        '            RAM: $RAM      
echo '   `$$b      "-.__             '		  IP:  $IP
echo '    `Y$$                       '
echo '     `Y$$.                     '
echo '       `$$b.                   '
echo '         `Y$$b.                '
echo '            `"Y$b._            '
echo '                `""""          '
