#!/bin/sh

user="${USER}"
hostname="${HOSTNAME:-${hostname:-$(hostname)}}"
host="$(cat /sys/devices/virtual/dmi/id/product_name)"
OS="$(cat /etc/os-release | grep PRETTY_NAME | sed 's/PRETTY_NAME=//g'| sed 's/"//g')"
#Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Packages="$(dpkg -l | grep -c ^i)"
Shell="$(basename "$SHELL")"
RAM="$(free -h | grep Mem: | awk '{print $3 "/" $2}')"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='Desktop'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='Desktop'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'

fi

# COLORS
c1="\e[91m" # Red
c2="\e[32m" # Light Green
c3="\e[33m" # Yellow
c4="\e[34m" # Calm Blue
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c7="\e[37m" # White
c8="\e[96m" # Cyan Blue 
c9="\e[39m" # Light Grey
c10="\e[40m" # Dark Grey
c11="\e[95m" # Light Purple
c12="\e[94m" # Light Blue
c20="\e[0m" # Normal

# An Error echo Wrapper
err0r()
{
	echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
	echo ""
	exit 86
}


# A Warning echo wrapper
warn ()
{
	echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$)tput sgr0)"
	echo ""
}



# A Message echo Wrapper
msg ()
{
	echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
}



echo ""
echo ${c5}"    .,,;;;::;,..                   "${c5}$user${c20}@${c5}$hostname
echo ${c5}"           '':ddd;:,.              "${c20}-----------
echo ${c5}"                 ''dPPd:,.         "${c5}OS:  ${c20}$OS
echo ${c5}"                     ':bSSb'.      "${c5}host:  ${c20}$host 
echo ${c5}"                        'PSSSd'    "${c5}Kernel:  ${c20}$Kernel 
echo ${c5}"                         .SSSSS'   "${c5}Uptime:  ${c20}$Uptime
echo ${c5}"                         ;SSSSSP   "${c5}Packages:  ${c20}$Packages
echo ${c5}"                      .:PSSSSSS'   "${c5}RAM:  ${c20}$RAM
echo ${c5}"                  .,:bSSSSSSS;'    "
echo ${c5}"             .,:dPSSSSSSSSb:'      "
echo ${c5}"      .,:;dbSSSSSSSSSSPd''         "
echo ${c5}" ,dbSSSSSSSSSSSSSSb:''             "
echo ${c5}":SSSSSSSSSSSSSb:''                 "
echo ${c5}" 'SSSSSbd:'''                      "
echo ${c5}"   '''''                           "
echo ${c20}""
