#!/usr/bin/env bash
# vim: noai:ts=4:sw=4:expandtab
# shellcheck source=/dev/null
# shellcheck disable=2009

###################################################################################
# This script uses lsb_release, lscpu, and glxinfo. make sure they are installed. #
###################################################################################
#
# START OF SCRIPT
#
#
clear ; clear

# Universal variables
user="${USER}\e[33m@"
Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Packages="$(dpkg -l | grep -c ^i)"
Uptime="$(uptime -p | sed 's/up //')"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
RAM="$(free -h | awk '/^Mem:/ {print $3 " / " $2}')"
OS1="$(lsb_release -si)"
OS="$(lsb_release -sirc)"

# colors
 c1="\e[31m" # Red
 c2="\e[32m" # Light Green
 c3="\e[33m" # Yellow
 c4="\e[34m"  # Calm Blue
 c5="\e[35m" # Violet
 c6="\e[36m" # Arch Blue
 c7="\e[37m" # White
 c8="\e[38m" # Sky Blue
 c9="\e[39m" # Light Grey
 c10="\e[30m" # Dark Grey
 c20="\e[0m" # Normal
         


# An Error echo wrapper
err0r()
{

    echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
    echo ""
    exit 86
}

# A Warning echo wrapper
warn()
{
 echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$(tput sgr0)"
 echo ""
}

# A Message echo wrapper
msg()
{
 echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
}



echo ""
echo -e "${c1}             8ZZZZZZ${c7}MMMMM              "     ${c1}${user}${c7}$(hostname)
echo -e "${c1}          .ZZZZZZZZZ${c7}MMMMMMM.           "     ${c1}OS: ${c7}$OS
echo -e "${c7}        MM${c1}ZZZZZZZZZ${c7}MMMMMMM${c1}ZZZZ         "     ${c1}Desktop: ${c7}$Desktop
echo -e "${c7}      MMMMM${c1}ZZZZZZZZ${c7}MMMMM${c1}ZZZZZZZM       "     ${c1}Kernel: ${c7}$Kernel
echo -e "${c7}     MMMMMMM${c1}ZZZZZZZ${c7}MMMM${c1}ZZZZZZZZZ.      "     ${c1}Packages: ${c7}$Packages
echo -e "${c7}    MMMMMMMMM${c1}ZZZZZZ${c7}MMM${c1}ZZZZZZZZZZZI     "     ${c1}Shell: ${c7}$Shell
echo -e "${c7}   MMMMMMMMMMM${c1}ZZZZZZ${c7}MM${c1}ZZZZZZZZZZ${c7}MMM    "     ${c1}CPU: ${c7}$CPU
echo -e "${c1}   .ZZZ${c7}MMMMMMMMMM${c1}IZZ${c7}MM${c1}ZZZZZ${c7}MMMMMMMMM   "     ${c1}GPU: ${c7}$GPU
echo -e "${c1}   ZZZZZZZ${c7}MMMMMMMM${c1}ZZ${c7}M${c1}ZZZZ${c7}MMMMMMMMMMM   "      ${c1}RAM: ${c7}$RAM
echo -e "${c1}   ZZZZZZZZZZZZZZZZ${c7}M${c1}Z${c7}MMMMMMMMMMMMMMM   "
echo -e "${c1}   .ZZZZZZZZZZZZZ${c7}MMM${c1}Z${c7}M${c1}ZZZZZZZZZZ${c7}MMMM   "
echo -e "${c1}   .ZZZZZZZZZZZ${c7}MMM${c1}7ZZ${c7}MM${c1}ZZZZZZZZZZ7${c7}M    "
echo -e "${c1}    ZZZZZZZZZ${c7}MMMM${c1}ZZZZ${c7}MMMM${c1}ZZZZZZZZ77     "
echo -e "${c7}     MMMMMMMMMMMM${c1}ZZZZZ${c7}MMMM${c1}ZZZZZZ77      "
echo -e "${c7}      MMMMMMMMMM${c1}7ZZZZZZ${c7}MMMMM${c1}ZZZ77       "
echo -e "${c7}       .MMMMMMM${c1}ZZZZZZZZ${c7}MMMMM${c1}Z7Z7        "
echo -e "${c7}         MMMMM${c1}ZZZZZZZZZ${c7}MMMMMMM         "
echo -e "${c1}           NZZZZZZZZZZZ${c7}MMMMM           "
echo -e "${c1}              ZZZZZZZZZ${c7}MM              ${c20}"
echo ""
